name: tapalert
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.17.4
  intl: ^0.18.1
  firebase_messaging: ^14.6.7 # or latest
  geolocator: ^11.0.0 # Use the latest version
  flutter_svg: ^2.2.0
  geocoding: ^2.0.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
