// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxAMoGinRtFx1rUSLq-EIdS89rrtZqTAs',
    appId: '1:37217913542:web:198a3b2d66befb604e65c7',
    messagingSenderId: '37217913542',
    projectId: 'tapalert-166b2',
    authDomain: 'tapalert-166b2.firebaseapp.com',
    storageBucket: 'tapalert-166b2.firebasestorage.app',
    measurementId: 'G-FLNV6K91P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqMdEtpxv4hlcFGscwoiqCcOukHUYrMjI',
    appId: '1:37217913542:android:6fa1af1d231ff2904e65c7',
    messagingSenderId: '37217913542',
    projectId: 'tapalert-166b2',
    storageBucket: 'tapalert-166b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo7-wWY2EoOfZ6nunhinOdh-iJq-6i9pQ',
    appId: '1:37217913542:ios:a6f8a2db80ed4ca84e65c7',
    messagingSenderId: '37217913542',
    projectId: 'tapalert-166b2',
    storageBucket: 'tapalert-166b2.firebasestorage.app',
    iosBundleId: 'com.example.tapalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo7-wWY2EoOfZ6nunhinOdh-iJq-6i9pQ',
    appId: '1:37217913542:ios:a6f8a2db80ed4ca84e65c7',
    messagingSenderId: '37217913542',
    projectId: 'tapalert-166b2',
    storageBucket: 'tapalert-166b2.firebasestorage.app',
    iosBundleId: 'com.example.tapalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxAMoGinRtFx1rUSLq-EIdS89rrtZqTAs',
    appId: '1:37217913542:web:d9ac7f10bb14a1074e65c7',
    messagingSenderId: '37217913542',
    projectId: 'tapalert-166b2',
    authDomain: 'tapalert-166b2.firebaseapp.com',
    storageBucket: 'tapalert-166b2.firebasestorage.app',
    measurementId: 'G-PFDKNTX4MT',
  );
}
